VERSION = -std=c++11
CFLAGS = -Wall

BUILD_DIR = ../build
LIB_DIR = ../lib
INCLUDE_DIR = ../include


all:
	echo "services"
	g++ $(VERSION) $(CFLAGS) -I $(INCLUDE_DIR) -c -o $(BUILD_DIR)/Core.o Core.cpp
